id: P86A39E93
initial_creation_type: ocr
source_metadata:
  volumes:
    291b749c6f264af9ab291d3cad807bcf:
      base_file: v037.txt
      image_group_id: I1PD95882
      title: འཇམ་པའི་དབྱངས་དཔའ་བོ་གཅིག་ཏུ་གྲུབ་པའི་སྒྲུབ་ཐབས།
      total_pages: 1379
      volume_number: 37
