id: D3143179C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-11T09:48:01+00:00'
last_modified: '2022-05-26T12:05:30.027863+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '1460':
      image_group_id: I1PD95882
      title: འཇམ་པའི་དབྱངས་དཔའ་བོ་གཅིག་ཏུ་གྲུབ་པའི་སྒྲུབ་ཐབས།
      total_pages: 1379
      order: 37
      base_file: 1460.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
